name: ejer2
on: push

jobs:
  ejer2:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Probar codigo
        run: python3 main.py
      - name: linter
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint

       
